version: '3.8'

services:
  borgstpoelten-server:
    build: ./school-server
    container_name: borgstpoelten-server
    environment:
      - EULA=TRUE
      - VERSION=1.21.10
      - MEMORY=5G
      - MAX_MEMORY=100G
      - TYPE=VANILLA
      - ONLINE_MODE=false
      - ENABLE_PROXY_CONNECTIONS=true
      - MOTD=BORGST PÃ¶llten Server
    volumes:
      - ./borgstpoelten/data:/data
      - ./borgstpoelten/datapacks:/data/datapacks  # Datapacks volume
    restart: unless-stopped
    networks:
      - borgstpoelten_net
    expose:
      - "25565"
    # No external port mapping since this would be handled by proxy if needed


networks:
  borgstpoelten_net:
    driver: bridge