version: '3.8'

services:
  play-server:
    build: ./school-server
    container_name: play-server
    environment:
      - EULA=TRUE
      - VERSION=1.21.10
      - MEMORY=5G
      - MAX_MEMORY=100G
      - TYPE=VANILLA
      - ONLINE_MODE=false
      - ENABLE_PROXY_CONNECTIONS=true
      - MOTD=Play Server
    volumes:
      - ./play/data:/data
      - ./play/datapacks:/data/datapacks  # Datapacks volume
    restart: unless-stopped
    networks:
      - play_net
    expose:
      - "25565"
    # No external port mapping since this would be handled by proxy if needed


networks:
  play_net:
    driver: bridge