version: '3.8'

services:
  bgstpoelten-server:
    build: ./school-server
    container_name: bgstpoelten-server
    environment:
      - EULA=TRUE
      - VERSION=1.21.10
      - MEMORY=5G
      - MAX_MEMORY=100G
      - TYPE=VANILLA
      - ONLINE_MODE=false
      - ENABLE_PROXY_CONNECTIONS=true
      - MOTD=BGST PÃ¶llten Server
    volumes:
      - ./bgstpoelten/data:/data
      - ./bgstpoelten/datapacks:/data/datapacks  # Datapacks volume
    restart: unless-stopped
    networks:
      - bgstpoelten_net
    expose:
      - "25565"
    # No external port mapping since this would be handled by proxy if needed


networks:
  bgstpoelten_net:
    driver: bridge