groups:
  rene:
  - admin
listeners:
- query_port: 25573
  motd: '&1Virtual Minecraft Network - Use /server commands to switch'
  tab_list: GLOBAL_PING
  uuid: 937bb4e1-5285-4c8e-8a7c-8aa72bcf97f0
  priorities:
  - mc-ilias  # Default server
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 99
  tab_size: 60
  force_default_server: true
  ping_passthrough: false
  proxy_protocol: false
  use_generic_kick: false
  connection_throttle: 4000
  connection_throttle_limit: 3
servers:
  mc-ilias:
    address: mc-ilias:25565
    restricted: false
    motd: '&6mc-ilias Server'
  mc-niilo:
    address: mc-niilo:25565
    restricted: false
    motd: '&6mc-niilo Server'
remote_ping_cache: -1
forge_support: true
network_compression_threshold: 256
prevent_proxy_connections: false
online_mode: false
attempt_connection_reduction: false
ip_forward: false