network_compression_threshold: 256
remote_ping_timeout: 5000
remote_ping_cache: -1
online_mode: true
forge_support: false
max_packets_per_second: 4096
ip_forward: true
disabled_commands:
- disabledcommandhere
max_packets_data_per_second: 33554432
player_limit: -1
reject_transfers: false
prevent_proxy_connections: false
connection_throttle_limit: 3
log_commands: false
connection_throttle: 4000
log_pings: true
stats: dda6340a-fbdb-4918-af26-aa66c9dc3b5d
groups:
  rene:
  - admin
servers:
  mc-ilias:
    address: mc-ilias:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-niilo:
    address: mc-niilo:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-bgstpoelten:
    address: mc-bgstpoelten:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-htlstp:
    address: mc-htlstp:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-borgstpoelten:
    address: mc-borgstpoelten:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-hakstpoelten:
    address: mc-hakstpoelten:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-basop-bafep-stp:
    address: mc-basop-bafep-stp:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  mc-play:
    address: mc-play:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
  - bungeecord.command.server
  - bungeecord.command.list
listeners:
- motd: '&1Virtual Minecraft Network - Use /server commands to switch'
  tab_list: GLOBAL_PING
  priorities:
  - mc-play
  host: 0.0.0.0:25565
  max_players: 250
  tab_size: 60
  force_default_server: true
  forced_hosts:
    mc.ikaria.dev: mc-ilias
    play.ikaria.dev: mc-ilias
    mc.kdlk.net: mc-niilo
    play.kdlk.net: mc-niilo
    bgstpoelten.lerncraft.xyz: mc-bgstpoelten
    htlstp.lerncraft.xyz: mc-htlstp
    borgstpoelten.lerncraft.xyz: mc-borgstpoelten
    hakstpoelten.lerncraft.xyz: mc-hakstpoelten
    basop-bafep-stp.lerncraft.xyz: mc-basop-bafep-stp
    live.lerncraft.xyz: mc-play
  bind_local_address: true
  ping_passthrough: false
  query_enabled: false
  query_port: 25577
  proxy_protocol: false
enforce_secure_profile: false
server_connect_timeout: 5000
timeout: 30000
