listeners:
- query_port: 25577
  motd: '&1Virtual Minecraft Network - Use /server commands to switch'
  tab_list: GLOBAL_PING
  query_enabled: true
  priorities:
  - mc-ilias
  host: 0.0.0.0:25565
  max_players: 250
  tab_size: 60
  force_default_server: true
  forced_hosts:
    pvp.lerncraft.de: mc-ilias
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
remote_ping_timeout: 5000
servers:
  mc-ilias:
    motd: '&1mc-ilias'
    address: mc-ilias:25565
    restricted: false
groups:
  rene:
  - admin